# This workflow will build a Java project with Maven

name: FF Snapshot Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone FF Repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Package Artifact
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FF Snapshot
          path: staging
